package fields_test

import (
	"testing"

	_ "github.com/iostrovok/kibana-fields/x/agent"
	_ "github.com/iostrovok/kibana-fields/x/as"
	_ "github.com/iostrovok/kibana-fields/x/base"
	_ "github.com/iostrovok/kibana-fields/x/client"
	_ "github.com/iostrovok/kibana-fields/x/cloud"
	_ "github.com/iostrovok/kibana-fields/x/code_signature"
	_ "github.com/iostrovok/kibana-fields/x/container"
	_ "github.com/iostrovok/kibana-fields/x/data_stream"
	_ "github.com/iostrovok/kibana-fields/x/destination"
	_ "github.com/iostrovok/kibana-fields/x/device"
	_ "github.com/iostrovok/kibana-fields/x/dll"
	_ "github.com/iostrovok/kibana-fields/x/dns"
	_ "github.com/iostrovok/kibana-fields/x/ecs"
	_ "github.com/iostrovok/kibana-fields/x/elf"
	_ "github.com/iostrovok/kibana-fields/x/email"
	_ "github.com/iostrovok/kibana-fields/x/error"
	_ "github.com/iostrovok/kibana-fields/x/event"
	_ "github.com/iostrovok/kibana-fields/x/faas"
	_ "github.com/iostrovok/kibana-fields/x/file"
	_ "github.com/iostrovok/kibana-fields/x/geo"
	_ "github.com/iostrovok/kibana-fields/x/group"
	_ "github.com/iostrovok/kibana-fields/x/hash"
	_ "github.com/iostrovok/kibana-fields/x/host"
	_ "github.com/iostrovok/kibana-fields/x/http"
	_ "github.com/iostrovok/kibana-fields/x/iface"
	_ "github.com/iostrovok/kibana-fields/x/log"
	_ "github.com/iostrovok/kibana-fields/x/macho"
	_ "github.com/iostrovok/kibana-fields/x/network"
	_ "github.com/iostrovok/kibana-fields/x/observer"
	_ "github.com/iostrovok/kibana-fields/x/orchestrator"
	_ "github.com/iostrovok/kibana-fields/x/organization"
	_ "github.com/iostrovok/kibana-fields/x/os"
	_ "github.com/iostrovok/kibana-fields/x/pe"
	_ "github.com/iostrovok/kibana-fields/x/pkg"
	_ "github.com/iostrovok/kibana-fields/x/process"
	_ "github.com/iostrovok/kibana-fields/x/registry"
	_ "github.com/iostrovok/kibana-fields/x/related"
	_ "github.com/iostrovok/kibana-fields/x/risk"
	_ "github.com/iostrovok/kibana-fields/x/rule"
	_ "github.com/iostrovok/kibana-fields/x/server"
	_ "github.com/iostrovok/kibana-fields/x/service"
	_ "github.com/iostrovok/kibana-fields/x/source"
	_ "github.com/iostrovok/kibana-fields/x/threat"
	_ "github.com/iostrovok/kibana-fields/x/tls"
	_ "github.com/iostrovok/kibana-fields/x/tracing"
	_ "github.com/iostrovok/kibana-fields/x/url"
	_ "github.com/iostrovok/kibana-fields/x/user"
	_ "github.com/iostrovok/kibana-fields/x/user_agent"
	_ "github.com/iostrovok/kibana-fields/x/vlan"
	_ "github.com/iostrovok/kibana-fields/x/vulnerability"
	_ "github.com/iostrovok/kibana-fields/x/x509"
)

func TestSyntax(t *testing.T) {
	t.Log("TestSyntax")
}
